Added an option of updating children packages
ottofeller/create-release-gh-action pull request #5
Opened 2022-02-18 07:17 UTC by quesabe

Closes PLA-75.

2022-02-18 13:41 UTC, gvidon requested changes

2022-02-18 13:41 UTC, gvidon commented on README.md
> +    update-children-path: packages/first packages/second packages/third
@quesabe can we have the list of repos own the shape of yaml array? Like this:
```yaml
update-children-path:
  - package/first
  - package/second
  - package/third

# OR

update-children-path: ['package/first', 'package/second', 'package/third']
```

2022-02-18 13:41 UTC, gvidon commented on README.md
> +    update-main-package_json: true
@quesabe please rename to this value (does this flag require the update of the root `packages.json`, and if not provided will only update nested `package.json`s):
```suggestion
    update-root-package-json: true
```

2022-02-18 13:41 UTC, gvidon commented on README.md
> +    update-children-path: packages/first packages/second packages/third
Please don't forget to update the docs accordingly.

2022-02-19 10:59 UTC, quesabe commented on README.md
> +    update-children-path: packages/first packages/second packages/third
Unfortunately actions take only strings as inputs. However the list might be separated with any spaces, including new lines. Thus a multiline string is a comparable option. I have included the syntax in an example in README.

2022-02-21 09:22 UTC, gvidon commented on README.md
> +    update-children-path: packages/first packages/second packages/third
@quesabe ok, got it, let's keep it like this.

2022-02-21 09:22 UTC, merged